# **Penting**
- Jangan mengubah atau menambahkan cell text yang sudah disediakan, Anda hanya perlu mengerjakan cell code yang sudah disediakan.
- Pastikan seluruh kriteria memiliki output yang sesuai, karena jika tidak ada output dianggap tidak selesai.
- Misal, Anda menggunakan df = df.dropna() silakan gunakan df.isnull().sum() sebagai tanda sudah berhasil. Silakan sesuaikan seluruh output dengan perintah yang sudah disediakan.
- Pastikan Anda melakukan Run All sebelum mengirimkan submission untuk memastikan seluruh cell berjalan dengan baik.
- Pastikan Anda menggunakan variabel df dari awal sampai akhir dan tidak diperbolehkan mengganti nama variabel tersebut.
- Hapus simbol pagar (#) pada kode yang bertipe komentar jika Anda menerapkan kriteria tambahan
- Biarkan simbol pagar (#) jika Anda tidak menerapkan kriteria tambahan
- Pastikan Anda mengerjakan sesuai section yang sudah diberikan tanpa mengubah judul atau header yang disediakan.

# **1. Import Library**
Pada tahap ini, Anda perlu mengimpor beberapa pustaka (library) Python yang dibutuhkan untuk analisis data dan pembangunan model machine learning.

In [1]:
import pandas as pd
import numpy as np
import joblib
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import StratifiedKFold, cross_val_score, GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix

# **2. Memuat Dataset dari Hasil Clustering**
Memuat dataset hasil clustering dari file CSV ke dalam variabel DataFrame.

In [2]:
# Gunakan dataset hasil clustering yang memiliki fitur Target
# Silakan gunakan dataset data_clustering jika tidak menerapkan Interpretasi Hasil Clustering [Advanced]
# Silakan gunakan dataset data_clustering_inverse jika menerapkan Interpretasi Hasil Clustering [Advanced]
# Lengkapi kode berikut

url="https://drive.google.com/uc?id=1KK2zu9POUPp3lpX_hVuAH90UPiLtrVUe"
df = pd.read_csv(url)

In [3]:
# Tampilkan 5 baris pertama dengan function head.
df.head()

,TransactionAmount,CustomerAge,TransactionDuration,LoginAttempts,AccountBalance,TransactionType,Location,CustomerOccupation,Channel,Target
0,14.09,70.000000,81.0,1.0,5112.21,Debit,San Diego,Doctor,ATM,1
1,376.24,68.000000,141.0,1.0,13758.91,Debit,Houston,Doctor,ATM,0
2,126.29,19.000000,56.0,1.0,1122.35,Debit,Mesa,Student,Online,0
3,184.50,26.000000,25.0,1.0,8569.06,Debit,Raleigh,Student,Online,1
4,13.45,44.678444,198.0,1.0,7429.40,Credit,Atlanta,Student,Online,2


# **3. Data Splitting**
Tahap Data Splitting bertujuan untuk memisahkan dataset menjadi dua bagian: data latih (training set) dan data uji (test set).

In [4]:
# Menggunakan train_test_split() untuk melakukan pembagian dataset.

X = df.drop("Target", axis=1)
y = df["Target"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# **4. Membangun Model Klasifikasi**
Setelah memilih algoritma klasifikasi yang sesuai, langkah selanjutnya adalah melatih model menggunakan data latih.

Berikut adalah rekomendasi tahapannya.
1. Menggunakan algoritma klasifikasi yaitu Decision Tree.
2. Latih model menggunakan data yang sudah dipisah.

In [5]:
# Buatlah model klasifikasi menggunakan Decision Tree

df_encoded = df.copy()
categorical_cols = ['TransactionType', 'Location', 'CustomerOccupation', 'Channel']

# encode kolom kategorikal
encoders = {}
for col in categorical_cols:
    le = LabelEncoder()
    df_encoded[col] = le.fit_transform(df_encoded[col])
    encoders[col] = le

# split dataset
X = df_encoded.drop('Target', axis=1)
y = df_encoded['Target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# bangun model Decision Tree
model_1 = DecisionTreeClassifier(
    max_depth=5,
    min_samples_split=2,
    min_samples_leaf=1,
    random_state=42
)

model_1.fit(X_train, y_train)
y_pred_train_model1 = model_1.predict(X_train)
y_pred_test_model1 = model_1.predict(X_test)

# evaluasi
train_acc = accuracy_score(y_train, y_pred_train_model1)
test_acc = accuracy_score(y_test, y_pred_test_model1)

print(f"\n HASIL DECISION TREE:")
print(f"Akurasi data latih: {train_acc}")
print(f"Akurasi data uji: {test_acc}")

# cross-validation
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
scores = cross_val_score(model_1, X, y, cv=cv, scoring='accuracy')
print(f"Akurasi cross-validation: {scores.mean()}")

print("\n DECISION TREE REPORT (TEST)")
print(classification_report(y_test, y_pred_test_model1))
print("\n DECISION TREE CONFUSION MATRIX (TEST)")
print(confusion_matrix(y_test, y_pred_test_model1))


 HASIL DECISION TREE:
Akurasi data latih: 1.0
Akurasi data uji: 1.0
Akurasi cross-validation: 1.0

 DECISION TREE REPORT (TEST)
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       177
           1       1.00      1.00      1.00       178
           2       1.00      1.00      1.00       148

    accuracy                           1.00       503
   macro avg       1.00      1.00      1.00       503
weighted avg       1.00      1.00      1.00       503


 DECISION TREE CONFUSION MATRIX (TEST)
[[177   0   0]
 [  0 178   0]
 [  0   0 148]]


In [6]:
# Menyimpan Model
# import joblib
joblib.dump(model_1, 'decision_tree_model.h5')

['decision_tree_model.h5']

# **5. Memenuhi Kriteria Skilled dan Advanced dalam Membangun Model Klasifikasi**



**Biarkan kosong jika tidak menerapkan kriteria skilled atau advanced**

In [7]:
# Melatih model menggunakan algoritma klasifikasi scikit-learn selain Decision Tree.

df_encoded = df.copy()
categorical_cols = ['TransactionType', 'Location', 'CustomerOccupation', 'Channel']

encoder = OneHotEncoder(drop="first")
encoded_cats = encoder.fit_transform(df_encoded[categorical_cols])
feature_names = encoder.get_feature_names_out(categorical_cols)
df_encoded_cats = pd.DataFrame(
    encoded_cats.toarray(),
    columns=feature_names,
    index=df_encoded.index
)

numerical_cols = ['TransactionAmount', 'CustomerAge', 'TransactionDuration', 'LoginAttempts', 'AccountBalance']
df_final_RF = pd.concat([df_encoded_cats, df_encoded[numerical_cols], df_encoded['Target']], axis=1) # Keep Target column

# split data
X = df_final_RF.drop('Target', axis=1)
y = df_final_RF['Target']
X_train_RF, X_test_RF, y_train_RF, y_test_RF = train_test_split(X, y, test_size=0.2, random_state=42)

# === 1. RANDOM FOREST ===
# bangun model RandomForest dengan GridSearch
paham_grid = {
    "n_estimators": [100, 150],
    "max_depth": [8, 9],
    "min_samples_split": [50,100],
    "min_samples_leaf": [25, 50],
    "max_features": ["sqrt", "log2"]
}

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

grid = GridSearchCV(
    RandomForestClassifier(random_state=42, n_jobs=-1),
    param_grid=paham_grid,
    cv=cv,
    scoring="accuracy",
    n_jobs=-1,
    verbose=0)
grid.fit(X_train_RF, y_train_RF)
best_rf = grid.best_estimator_

# scalling untuk model yang membutuhkan
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_RF)
X_test_scaled = scaler.transform(X_test_RF)

# === 2. LOGISTIC REGRESSION ===
logreg = LogisticRegression(random_state=42)
logreg.fit(X_train_scaled, y_train_RF)

# === 3. KNN ===
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_scaled, y_train_RF)

# === 4.SUPPORT VECTOR MACHINE ===
param_svm = {
    'C': [0.1, 1, 10],
    'gamma': ["scale", 0.1, 0.01],
    'kernel': ['rbf']
}
grid_svm = GridSearchCV(
    SVC(random_state=42),
    param_svm,
    cv=3,
    scoring="accuracy")
grid_svm.fit(X_train_scaled, y_train_RF)
best_svm = grid_svm.best_estimator_

svm = SVC(kernel='rbf', random_state=42)
svm.fit(X_train_scaled, y_train_RF)


,C,1.0
,kernel,'rbf'
,degree,3
,gamma,'scale'
,coef0,0.0
,shrinking,True
,probability,False
,tol,0.001
,cache_size,200
,class_weight,None
,verbose,False


In [8]:
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada seluruh algoritma yang sudah dibuat.

print("\n=== RANDOM FOREST ===")
print("Best params for Random Forest:", grid.best_params_)
print(f"CV score:, {grid.best_score_:.4f}")

def eval_model(model, Xtr, ytr, Xte, yte):
    ytr_pred = model.predict(Xtr)
    yte_pred = model.predict(Xte)
    acc_tr = accuracy_score(ytr, ytr_pred)
    acc_te = accuracy_score(yte, yte_pred)
    prec = precision_score(yte, yte_pred, average='weighted')
    rec = recall_score(yte, yte_pred, average='weighted')
    f1 = f1_score(yte, yte_pred, average='weighted')

    print(f"Akurasi data Train: {acc_tr:.4f}")
    print(f"Akurasi data Test: {acc_te:.4f}")
    print(f"Presisi (weighted): {prec:.4f}")
    print(f"Recall  (weighted): {rec:.4f}")
    print(f"F1-Score(weighted): {f1:.4f}")

eval_model(best_rf, X_train_RF, y_train_RF, X_test_RF, y_test_RF)
print(classification_report(y_test_RF, best_rf.predict(X_test_RF)))
print(confusion_matrix(y_test_RF, best_rf.predict(X_test_RF)))

print("\n=== LOGISTIC REGRESSION ===")
eval_model(logreg, X_train_scaled, y_train_RF, X_test_scaled, y_test_RF)
print(classification_report(y_test_RF, logreg.predict(X_test_scaled)))
print(confusion_matrix(y_test_RF, logreg.predict(X_test_scaled)))

print("\n=== KNN ===")
eval_model(knn, X_train_scaled, y_train_RF, X_test_scaled, y_test_RF)
print(classification_report(y_test_RF, knn.predict(X_test_scaled)))
print(confusion_matrix(y_test_RF, knn.predict(X_test_scaled)))

print("\n=== SVM ===")
eval_model(best_svm, X_train_scaled, y_train_RF, X_test_scaled, y_test_RF)
print(classification_report(y_test_RF, best_svm.predict(X_test_scaled)))
print(confusion_matrix(y_test_RF, best_svm.predict(X_test_scaled)))


=== RANDOM FOREST ===
Best params for Random Forest: {'max_depth': 9, 'max_features': 'sqrt', 'min_samples_leaf': 25, 'min_samples_split': 100, 'n_estimators': 150}
CV score:, 0.8156
Akurasi data Train: 0.9299
Akurasi data Test: 0.9105
Presisi (weighted): 0.9286
Recall  (weighted): 0.9105
F1-Score(weighted): 0.9120
              precision    recall  f1-score   support

           0       1.00      0.83      0.91       177
           1       0.80      1.00      0.89       178
           2       1.00      0.90      0.95       148

    accuracy                           0.91       503
   macro avg       0.93      0.91      0.91       503
weighted avg       0.93      0.91      0.91       503

[[147  30   0]
 [  0 178   0]
 [  0  15 133]]

=== LOGISTIC REGRESSION ===
Akurasi data Train: 1.0000
Akurasi data Test: 1.0000
Presisi (weighted): 1.0000
Recall  (weighted): 1.0000
F1-Score(weighted): 1.0000
              precision    recall  f1-score   support

           0       1.00      1.00    

In [9]:
# Menyimpan Model Selain Decision Tree
# Model ini bisa lebih dari satu
joblib.dump(best_rf, 'explore_RandomForest_classification.h5')
joblib.dump(logreg, 'explore_LogisticRegression_classification.h5')
joblib.dump(knn, 'explore_KNN_classification.h5')
joblib.dump(best_svm, 'explore_SVM_classification.h5')

['explore_SVM_classification.h5']

Hyperparameter Tuning Model

Pilih salah satu algoritma yang ingin Anda tuning

In [10]:
# Lakukan Hyperparameter Tuning dan Latih ulang.
# Lakukan dalam satu cell ini saja.

# hyperparameter tuning untuk model Decision Tree
paham_grid = {
    'max_depth': [1, 2, 3],
    'min_samples_split': [50, 100, 150],
    'min_samples_leaf': [50, 100, 150],
    'max_features': [1, 2, 'log2'],
    'ccp_alpha': [0.05, 0.1, 0.2, 0.3]
}

# cross validation
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
grid = GridSearchCV(
    DecisionTreeClassifier(random_state=42),
    param_grid=paham_grid,
    cv=cv,
    scoring="accuracy",
    n_jobs=-1)
grid.fit(X_train, y_train)
best_dt = grid.best_estimator_

In [11]:
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada algoritma yang sudah dituning.

y_pred_train_model1 = best_dt.predict(X_train)
y_pred_test_model1 = best_dt.predict(X_test)
train_acc = accuracy_score(y_train, y_pred_train_model1)
test_acc = accuracy_score(y_test, y_pred_test_model1)
cv_scores = cross_val_score(best_dt, X_train, y_train, cv=cv, scoring='accuracy')

print(f"\n HASIL DECISION TREE (TUNING):")
print(f"Akurasi data latih: {train_acc}")
print(f"Akurasi data uji: {test_acc}")
print(f"Akurasi cross-validation: {cv_scores.mean()}")
print("\n DECISION TREE REPORT (TEST)")
print(classification_report(y_test, y_pred_test_model1))
print("\n DECISION TREE CONFUSION MATRIX (TEST)")
print(confusion_matrix(y_test, y_pred_test_model1))


 HASIL DECISION TREE (TUNING):
Akurasi data latih: 0.9761431411530815
Akurasi data uji: 0.9701789264413518
Akurasi cross-validation: 0.9885695591521302

 DECISION TREE REPORT (TEST)
              precision    recall  f1-score   support

           0       1.00      0.92      0.96       177
           1       1.00      1.00      1.00       178
           2       0.91      1.00      0.95       148

    accuracy                           0.97       503
   macro avg       0.97      0.97      0.97       503
weighted avg       0.97      0.97      0.97       503


 DECISION TREE CONFUSION MATRIX (TEST)
[[162   0  15]
 [  0 178   0]
 [  0   0 148]]


In [12]:
# Menyimpan Model hasil tuning
# import joblib
joblib.dump(best_dt, 'tuning_classification.h5')

['tuning_classification.h5']

End of Code